[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "qscm"
version = "0.1.0"
description = "Structural Causal Model inspired architecture"
requires-python = ">=3.12"
dependencies = [
    "networkx",
    "plotly",
    "pydot",
]

[project.scripts]
acronyms = "qscm.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
